[project]
name = "wheresmymovie"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "ravian-h", email = "ravian.hendriks@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[project.scripts]
wheresmymovie = "wheresmymovie:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
